services:
  govh:
    build:
      context: .
      dockerfile: Dockerfile
    # You can use nicojmn/govh-renew-ip:latest if you don't want to build the image
    environment:
      - OVH_ENDPOINT=${OVH_ENDPOINT}
      - OVH_APP_KEY=${OVH_APP_KEY}
      - OVH_APP_SECRET=${OVH_APP_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
      - DOMAIN=${DOMAIN}
      - TIME_INTERVAL=${TIME_INTERVAL}
    restart: unless-stopped
