name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag govh-renew-ip:${{ github.sha }}

    - name: Login to dockerhub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push images
      run: |
        docker tag db-cheatsheet:${{ github.sha }} ${{ secrets.DOCKER_USER }}/govh-renew-ip:${{ github.sha }}
        docker tag db-cheatsheet:${{ github.sha }} ${{ secrets.DOCKER_USER }}/govh-renew-ip:latest
        docker push ${{ secrets.DOCKER_USER }}/govh-renew-ip:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USER }}/govh-renew-ip:latest
